# Generated by Django 3.2 on 2021-04-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profId', models.UUIDField()),
                ('fullname', models.CharField(max_length=60)),
            ],
        ),
    ]
