# Generated by Django 3.2 on 2021-04-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDjangoApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.UUIDField()),
                ('className', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteId', models.UUIDField()),
                ('studentId', models.UUIDField()),
                ('subjectId', models.UUIDField()),
                ('mark', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.UUIDField()),
                ('fullname', models.CharField(max_length=60)),
                ('classId', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectId', models.UUIDField()),
                ('classId', models.UUIDField()),
                ('profId', models.UUIDField()),
                ('subjectName', models.CharField(max_length=60)),
            ],
        ),
    ]
